// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9XLmTNIW2K972iAiq0p9lfv1gPLZa03M',
    appId: '1:146928850049:web:25ba88378c8ce605f46980',
    messagingSenderId: '146928850049',
    projectId: 'millio-22528',
    authDomain: 'millio-22528.firebaseapp.com',
    storageBucket: 'millio-22528.firebasestorage.app',
    measurementId: 'G-932590CJP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwesUD1LfrKqoEMj0Pmsl0rKvAasx8cgw',
    appId: '1:146928850049:android:082aa103621b7635f46980',
    messagingSenderId: '146928850049',
    projectId: 'millio-22528',
    storageBucket: 'millio-22528.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYT8ARDxidSeHhlxV89kxDjEL48s6rBTs',
    appId: '1:146928850049:ios:43e2e439367ab445f46980',
    messagingSenderId: '146928850049',
    projectId: 'millio-22528',
    storageBucket: 'millio-22528.firebasestorage.app',
    iosBundleId: 'com.example.millio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYT8ARDxidSeHhlxV89kxDjEL48s6rBTs',
    appId: '1:146928850049:ios:43e2e439367ab445f46980',
    messagingSenderId: '146928850049',
    projectId: 'millio-22528',
    storageBucket: 'millio-22528.firebasestorage.app',
    iosBundleId: 'com.example.millio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9XLmTNIW2K972iAiq0p9lfv1gPLZa03M',
    appId: '1:146928850049:web:21964808d1c96a4cf46980',
    messagingSenderId: '146928850049',
    projectId: 'millio-22528',
    authDomain: 'millio-22528.firebaseapp.com',
    storageBucket: 'millio-22528.firebasestorage.app',
    measurementId: 'G-2183ZZBMXG',
  );

}